matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx

script:
  - test "$TRAVIS_OS_NAME" = "osx" && brew install re2
  - pip install Cython
  - pip install https://github.com/joerick/cibuildwheel/archive/master.zip
  - cibuildwheel --output-dir wheelhouse

env:
  global:
    - CIBW_BEFORE_BUILD_LINUX="yum install -y re2-devel; {pip} install Cython"
    - CIBW_BEFORE_BUILD_MACOS="{pip} install Cython"
